"use client";
import { Fragment } from "react";
import Link from "next/link";
import { useState } from "react";
import { Chip, Insight, Kpis, PageHead, Panel, Prog, Tabs } from "@/components/ui";
import { Bars, HBars, LineChart, Ring } from "@/components/charts";
import DataTable from "@/components/table";
import { AGING, AMCS, MONTHS, PROFIT, SERIES, TERRITORIES } from "@/data/ops";
import { BRANCHES, CUSTOMERS, TECHS } from "@/data/core";
import { inr, full } from "@/lib/format";

const TABS = ["Overview", "Financial", "Profitability", "SLA", "First-Time Fix", "Repeat Complaints", "Customers & CLV", "Job Ranking", "AMC Profitability"];
export default function Reports() {
  const [tab, setTab] = useState("Overview");
  const ftfTech = [...TECHS].sort((a, b) => b.ftf - a.ftf);
  const jobs = [["JOB-2790", "Orchid Diagnostics", "PCB replacement", 8400, 4980], ["JOB-2802", "Maa Ganga Clinic", "RO service", 3600, 1520], ["JOB-2781", "Hotel Capital", "Wiring repair", 14800, 8800], ["JOB-2773", "Radhey Showroom", "DVR + cameras", 41200, 29800], ["JOB-2760", "Sai Nursing Home", "Emergency electrical", 6200, 7900], ["JOB-2751", "Royal Residency", "AC repair (3 callbacks)", 5400, 6700]].map(([id, c, s, rev, cost]) => ({ id, c, s, rev, cost, profit: rev - cost, m: ((rev - cost) / rev) * 100, why: rev - cost < 0 ? (cost > rev * 1.2 ? "Repeat visits + emergency travel" : "Parts cost exceeded estimate") : "" }));
  return (
    <div className="page">
      <PageHead title="Reports & Analytics" sub="Profitability, SLA, quality and money — the numbers behind the operation." />
      <Tabs tabs={TABS} value={tab} onChange={setTab} />
      {tab === "Overview" && (<>
        <div className="grid g3" style={{ marginBottom: 14 }}>
          <Panel title="Jobs by status" sub="today"><Bars data={[["Completed", 58], ["In progress", 14], ["Delayed", 8], ["Unassigned", 6]].map(([k, v], i) => ({ k, v, color: ["green", "blue", "amber", "red"][i] }))} height={160} /></Panel>
          <Panel title="Revenue trend" sub="₹ lakh"><LineChart labels={MONTHS} series={[{ name: "Revenue", data: SERIES.revenue, color: "ink" }]} fmt={(v) => v} /></Panel>
          <Panel title="SLA trend" sub="%"><LineChart labels={MONTHS} series={[{ name: "SLA", data: SERIES.sla, color: "blue" }]} fmt={(v) => v + "%"} min={84} /></Panel>
          <Panel title="Technician utilisation" sub="% of paid hours"><HBars items={BRANCHES.map((b) => ({ k: b.name, v: 78 + (b.techs % 9) }))} fmt={(v) => v + "%"} max={100} tone="blue" /></Panel>
          <Panel title="First-time fix" sub="%"><LineChart labels={MONTHS} series={[{ name: "FTF", data: SERIES.ftf, color: "green" }]} fmt={(v) => v + "%"} min={80} /></Panel>
          <Panel title="Revenue by service type" sub="₹ lakh MTD"><HBars items={[["Commercial AC", 28.4], ["Residential AC", 14.2], ["CCTV", 11.8], ["Electrical", 10.6], ["RO / Water", 9.1], ["Appliance", 6.9], ["Facility", 3.6]].map(([k, v]) => ({ k, v }))} fmt={(v) => "₹" + v + "L"} /></Panel>
          <Panel title="AMC renewals" sub="next 6 months"><Bars data={[["Oct", 7], ["Nov", 12], ["Dec", 21], ["Jan", 34], ["Feb", 28], ["Mar", 41]].map(([k, v]) => ({ k, v }))} height={150} /></Panel>
          <Panel title="Customer satisfaction" sub="★"><LineChart labels={MONTHS} series={[{ name: "CSAT", data: SERIES.csat, color: "green" }]} fmt={(v) => v} min={4.1} /></Panel>
          <Panel title="Parts consumption" sub="units this month"><HBars items={[["Capacitors", 412], ["R410A gas (kg)", 366], ["Filters", 290], ["RO membranes", 118], ["Compressors", 41]].map(([k, v]) => ({ k, v }))} tone="amber" /></Panel>
        </div></>)}
      {tab === "Financial" && (<>
        <Insight tone="a"><b>Gross profit is ₹29.1L (34.4% margin).</b> Parts carry the highest margin; travel cost is up 11% on Patna’s longer routes.</Insight>
        <Kpis cols={8} items={[["Revenue this month", "₹84.6L"], ["Collections", "₹69.4L"], ["Outstanding", "₹16.8L"], ["Technician cost", "₹31.4L"], ["Parts cost", "₹16.5L"], ["Travel cost", "₹4.1L"], ["Gross profit", "₹29.1L"], ["AMC revenue", "₹17.2L"]].map(([label, value], i) => ({ label, value, tone: i === 2 ? "r" : i === 6 ? "g" : undefined }))} />
        <div className="grid g2"><Panel title="Revenue dashboard"><dl className="kv">{[["Service revenue", PROFIT.rev[0][1]], ["Parts revenue", PROFIT.rev[1][1]], ["AMC revenue", PROFIT.rev[2][1]], ["Installation revenue", PROFIT.rev[3][1]]].map(([a, b]) => <Fragment key={a}><dt>{a}</dt><dd>{full(b)}</dd></Fragment>)}<dt>Collected</dt><dd className="pos">{full(6940000)}</dd><dt>Outstanding</dt><dd className="neg">{full(1680000)}</dd><dt>Discount given</dt><dd>{full(184000)}</dd><dt className="tot">Gross profit</dt><dd className="tot">{full(2910000)}</dd></dl></Panel><Panel title="Revenue vs collections" sub="₹ lakh"><LineChart labels={MONTHS} series={[{ name: "Revenue", data: SERIES.revenue, color: "ink" }, { name: "Collections", data: SERIES.collections, color: "green", dash: true }]} fmt={(v) => v} /></Panel></div></>)}
      {tab === "Profitability" && (<>
        <Insight><b>CCTV is the lowest-margin service at 31%</b> — installation overruns on cabling. Commercial AC (36%) earns the most absolute profit; RO has the best margin at 42%.</Insight>
        <div className="grid g2" style={{ marginBottom: 14 }}><Panel title="Margin by service type"><HBars items={PROFIT.service.map(([k, v]) => ({ k, v }))} fmt={(v) => v + "%"} max={50} tone="green" /></Panel><Panel title="Margin by branch"><HBars items={[["Ranchi", 37], ["Jamshedpur", 35], ["Dhanbad", 33], ["Patna", 29]].map(([k, v]) => ({ k, v }))} fmt={(v) => v + "%"} max={50} tone="blue" /></Panel><Panel title="Margin by asset type"><HBars items={[["Split AC", 39], ["Cassette AC", 35], ["RO", 42], ["CCTV camera", 30], ["DVR", 33], ["Electrical panel", 34], ["Generator", 28]].map(([k, v]) => ({ k, v }))} fmt={(v) => v + "%"} max={50} /></Panel><Panel title="Top technicians by revenue"><HBars items={[...TECHS].sort((a, b) => b.rev - a.rev).slice(0, 6).map((t) => ({ k: t.name, v: t.rev }))} fmt={(v) => `₹${v}L`} tone="green" /></Panel></div></>)}
      {tab === "SLA" && (<>
        <Insight tone="a"><b>4 jobs are at risk of breaching SLA in the next hour</b>, including JOB-2841 (Apex Mall, 38 min left). Patna’s average response is 58 min — the slowest zone.</Insight>
        <Kpis cols={5} items={[{ label: "Within SLA", value: "92%", tone: "g" }, { label: "SLA breached (MTD)", value: "47", tone: "r" }, { label: "At risk now", value: "4", tone: "a" }, { label: "Avg response time", value: "41 min" }, { label: "Avg resolution time", value: "3h 12m" }]} />
        <div className="grid g2"><Panel title="SLA by priority"><table className="tbl"><thead><tr><th>Priority</th><th>Target</th><th className="r">Within SLA</th><th className="r">Avg resolution</th></tr></thead><tbody>{[["Emergency", "2 hours", 88, "1h 34m"], ["High", "4 hours", 91, "3h 02m"], ["Normal", "24 hours", 96, "9h 40m"], ["AMC", "As contracted", 94, "—"]].map(([p, t, w, r]) => <tr key={p}><td><Chip tone={p === "Emergency" ? "r" : p === "High" ? "a" : p === "AMC" ? "b" : "n"}>{p}</Chip></td><td>{t}</td><td className="r"><b>{w}%</b></td><td className="r">{r}</td></tr>)}</tbody></table></Panel><Panel title="By territory"><HBars items={TERRITORIES.map((z) => ({ k: z.zone, v: z.sla }))} fmt={(v) => v + "%"} max={100} tone="blue" /></Panel></div></>)}
      {tab === "First-Time Fix" && (<>
        <Insight><b>13% of jobs require a repeat visit, adding approximately ₹1.6L monthly operational cost.</b> Top-quartile technicians fix 90%+ on the first visit.</Insight>
        <div className="grid g2"><Panel title="By technician" sub="top 8"><HBars items={ftfTech.slice(0, 8).map((t) => ({ k: t.name, v: t.ftf }))} fmt={(v) => v + "%"} max={100} tone="green" /></Panel><Panel title="Bottom 5"><HBars items={ftfTech.slice(-5).reverse().map((t) => ({ k: t.name, v: t.ftf }))} fmt={(v) => v + "%"} max={100} tone="amber" /></Panel><Panel title="By service category"><HBars items={[["RO / Water", 91], ["Residential AC", 89], ["CCTV", 86], ["Commercial AC", 84], ["Electrical", 88], ["Appliance", 82]].map(([k, v]) => ({ k, v }))} fmt={(v) => v + "%"} max={100} /></Panel><Panel title="By branch"><HBars items={BRANCHES.map((b) => ({ k: b.name, v: b.ftf }))} fmt={(v) => v + "%"} max={100} tone="blue" /></Panel></div></>)}
      {tab === "Repeat Complaints" && (<>
        <Insight tone="r"><b>Cooling issue: 38 repeat complaints, most commonly caused by gas leakage.</b> Repeat complaints are up 18% in Ranchi Central — mostly 4–6 year old splits.</Insight>
        <div className="grid g2"><Panel title="Common causes"><HBars items={[["Gas leakage", 38], ["Capacitor failure", 22], ["PCB fault", 14], ["Drain blockage", 11], ["Compressor wear", 9]].map(([k, v]) => ({ k, v }))} tone="amber" /></Panel><Panel title="Customers with repeats" tight>{[["Apex Mall", "AC-28941 · 4 complaints"], ["Gupta Office", "gas leakage · 3"], ["Royal Residency", "geyser · 3"], ["Eastern Public School", "RO · 2"]].map(([c, d]) => <div key={c} className="feed-i"><b style={{ flex: 1, fontWeight: 560 }}>{c}</b><span className="muted">{d}</span></div>)}</Panel><Panel title="Assets with repeated failures" tight>{[["AC-28941", "Blue Star Cassette 5T", "4 / 90d"], ["AC-27388", "Daikin Split 1.5T", "3 / 90d"], ["RO-28012", "Kent RO Supreme", "3 / 90d"]].map(([i, m, n]) => <Link key={i} href={`/assets/${i}`} className="feed-i"><b className="mono">{i}</b><span style={{ flex: 1 }}>{m}</span><b className="neg">{n}</b></Link>)}</Panel><Panel title="Technicians with callbacks"><HBars items={[...TECHS].sort((a, b) => a.ftf - b.ftf).slice(0, 5).map((t) => ({ k: t.name, v: Math.round((100 - t.ftf) * t.month[0] / 100) }))} tone="red" /></Panel></div></>)}
      {tab === "Customers & CLV" && (<>
        <div className="grid g4" style={{ marginBottom: 14 }}>{[["Enterprise", 312], ["AMC Customer", 1204], ["Residential", 5480], ["High Value", 186], ["At Risk", 94], ["Inactive", 640], ["Payment Risk", 61]].map(([s, n]) => <div key={s} className="panel" style={{ padding: 14 }}><div className="lbl">{s}</div><div className="big">{n.toLocaleString("en-IN")}</div></div>)}</div>
        <DataTable title="Customer lifetime value" rows={[...CUSTOMERS].sort((a, b) => b.ltv - a.ltv).slice(0, 25)} cols={[{ key: "name", label: "Customer", render: (c) => <Link href={`/customers/${c.id}`} style={{ fontWeight: 560 }}>{c.name}</Link> }, { key: "ltv", label: "Lifetime revenue", right: true, render: (c) => inr(c.ltv) }, { key: "freq", label: "Visits / year", right: true, render: (c) => 4 + c.assets % 22, sort: (c) => 4 + c.assets % 22 }, { key: "amc", label: "AMC value", right: true, render: (c) => inr(c.amcs * 210000), sort: (c) => c.amcs }, { key: "parts", label: "Parts revenue", right: true, render: (c) => inr(c.ltv * 0.27), sort: (c) => c.ltv }, { key: "out", label: "Outstanding", right: true, render: (c) => c.out ? <b className="neg">{inr(c.out)}</b> : "—" }, { key: "m", label: "Profitability", right: true, render: (c) => `${31 + c.id.charCodeAt(3) % 10}%`, sort: (c) => c.id.charCodeAt(3) }]} /></>)}
      {tab === "Job Ranking" && (<DataTable title="Job profitability" rows={jobs} cols={[{ key: "id", label: "Job", style: { fontFamily: "var(--font-geist-mono)" } }, { key: "c", label: "Customer" }, { key: "s", label: "Service" }, { key: "rev", label: "Revenue", right: true, render: (j) => full(j.rev) }, { key: "cost", label: "Cost", right: true, render: (j) => full(j.cost) }, { key: "profit", label: "Profit", right: true, render: (j) => <b className={j.profit < 0 ? "neg" : "pos"}>{full(j.profit)}</b> }, { key: "m", label: "Margin", right: true, render: (j) => <b className={j.m < 0 ? "neg" : j.m < 25 ? "warn" : "pos"}>{j.m.toFixed(1)}%</b> }, { key: "why", label: "Reason for loss", render: (j) => j.why || <span className="faint">—</span> }]} views={[{ name: "All" }, { name: "Most profitable", filter: (j) => j.m > 38 }, { name: "Low margin", filter: (j) => j.m >= 0 && j.m < 25 }, { name: "Loss-making", filter: (j) => j.m < 0 }]} />)}
      {tab === "AMC Profitability" && (<><Insight tone="r"><b>{AMCS.filter((a) => (a.value - a.cost) / a.value < 0.08).length} AMCs earn under 8% margin.</b> Reprice at renewal or cap emergency callouts.</Insight><DataTable title="AMC profitability" rows={AMCS} cols={[{ key: "id", label: "Contract", style: { fontFamily: "var(--font-geist-mono)" } }, { key: "cust", label: "Customer" }, { key: "value", label: "Revenue", right: true, render: (a) => inr(a.value) }, { key: "used", label: "Visits used", right: true, render: (a) => `${a.used}/${a.incl}`, sort: (a) => a.used }, { key: "cost", label: "Total cost", right: true, render: (a) => inr(a.cost) }, { key: "profit", label: "Profit", right: true, render: (a) => <b className={a.value < a.cost ? "neg" : ""}>{inr(a.value - a.cost)}</b>, sort: (a) => a.value - a.cost }, { key: "m", label: "Margin", right: true, render: (a) => { const m = ((a.value - a.cost) / a.value) * 100; return <Chip tone={m < 8 ? "r" : m < 25 ? "a" : "g"}>{m.toFixed(0)}%</Chip>; }, sort: (a) => (a.value - a.cost) / a.value }]} views={[{ name: "All" }, { name: "Unprofitable", filter: (a) => (a.value - a.cost) / a.value < 0.08 }]} initialView={0} /></>)}
    </div>
  );
}
