import { JOBS, AMCS, PARTS, INVOICES } from "@/data/ops";
import { TECHS, CUSTOMERS, BRANCHES, LOCALITIES, dist, techById } from "@/data/core";
import { inr } from "@/lib/format";

export const SUGGESTED = ["Which jobs need attention right now?", "Which jobs are delayed?", "Which technicians are free near Lalpur?", "Which customers have repeat complaints?", "Which AMCs expire this month?", "Which technicians have the highest first-time-fix rate?", "Which jobs are waiting for parts?", "How much money is overdue?", "Which service type is most profitable?", "Which customer generated the most revenue?", "Which branch has the lowest SLA performance?"];

export function answer(q) {
  const s = q.toLowerCase();
  const J = (id) => JOBS.find((j) => j.id === id);
  if (/attention|urgent|need/.test(s) && /job/.test(s)) {
    const list = [["JOB-2841", "Emergency AC breakdown", "SLA remaining: 38 min · No technician assigned", "/dispatch"], ["JOB-2818", "Technician delayed by 28 min", "Rohit Kumar · customer waiting", "/jobs/JOB-2818"], ["JOB-2794", "Waiting for compressor part", "0 in Ranchi stock · 2 in transit from Dhanbad", "/jobs/JOB-2794"], ["JOB-2776", "Customer approval pending for 3 hours", "Estimate ₹22,400 · technician idle on site", "/jobs/JOB-2776"], ...JOBS.filter((j) => j.status === "Escalated").slice(0, 3).map((j) => [j.id, `${j.service} — escalated`, "Supervisor review open", `/jobs/${j.id}`])];
    return { title: `${list.length} jobs need immediate attention.`, items: list.map(([id, a, b, href]) => ({ id, head: `${J(id)?.customer ?? ""}`, a, b, href })), note: "Estimated revenue at risk: ₹1.86L", actions: [["Open dispatch board", "/dispatch"]] };
  }
  if (/delayed/.test(s)) { const l = JOBS.filter((j) => j.bucket === "delayed"); return { title: `${l.length} jobs are delayed.`, items: l.map((j) => ({ id: j.id, head: j.customer, a: j.service, b: `${j.status} · running ${j.delay} min late`, href: `/jobs/${j.id}` })), note: `Delayed work value: ${inr(l.reduce((a, j) => a + j.value, 0))}` }; }
  if (/free|available/.test(s)) { const lp = LOCALITIES.ranchi.Lalpur; const l = TECHS.filter((t) => t.status === "available" && t.branch === "ranchi").map((t) => ({ t, d: dist(t.pos, lp) })).sort((a, b) => a.d - b.d); return { title: `${l.length} technicians are free in Ranchi — closest to Lalpur first.`, items: l.map(({ t, d }) => ({ id: t.name, head: t.title, a: `${(t.id === "T02" ? 2.9 : d).toFixed(1)} km from Lalpur`, b: `${t.skills.join(", ")} · ★ ${t.rating} · FTF ${t.ftf}%`, href: `/technicians/${t.id}` })), note: "Amit Singh is the fastest to reach Apex Mall; Rohit Kumar is the best skill match." }; }
  if (/repeat/.test(s)) return { title: "4 customers have repeat complaints.", items: [["Apex Mall", "AC-28941 — 4 cooling complaints in 90 days", "₹28,400 spent · replacement recommended", "/assets/AC-28941"], ["Gupta Office", "Gas leakage — 3 visits", "Rated 2★ · escalation open", "/customers/C009"], ["Royal Residency", "Geyser element — 3 visits", "At Risk segment", "/customers/C008"], ["Eastern Public School", "RO low flow — 2 visits", "Payment risk", "/customers/C005"]].map(([h, a, b, href]) => ({ id: h, head: "", a, b, href })), note: "Cooling issues: 38 repeat complaints — most common cause is gas leakage." };
  if (/amc/.test(s)) { const l = AMCS.filter((a) => a.status === "Expiring"); return { title: `${l.length} AMCs expire this month.`, items: l.map((a) => ({ id: a.id, head: a.cust, a: `${inr(a.value)} · expires ${a.expiry}`, b: `Renewal: ${a.renewal || "—"} · probability ${a.prob}%`, href: `/amc/${a.id}` })), note: `Renewal value at stake: ${inr(l.reduce((a, x) => a + x.value, 0))}` }; }
  if (/first.?time|fix/.test(s)) { const l = [...TECHS].sort((a, b) => b.ftf - a.ftf).slice(0, 5); return { title: "Top 5 technicians by first-time-fix.", items: l.map((t) => ({ id: t.name, head: t.title, a: `${t.ftf}% first-time fix`, b: `★ ${t.rating} · ${t.month[1]} jobs this month`, href: `/technicians/${t.id}` })), note: "Company average is 87%." }; }
  if (/part/.test(s)) { const l = JOBS.filter((j) => j.status === "Parts Pending"); return { title: `${l.length} jobs are waiting for parts.`, items: l.map((j) => ({ id: j.id, head: j.customer, a: j.part || "Spare part pending", b: `Value ${inr(j.value)}`, href: `/jobs/${j.id}` })), note: "Compressor 1.5 Ton: 0 in Ranchi, 2 in transit from Dhanbad (ETA 3:40 PM) — blocking ₹84,000 of work." }; }
  if (/overdue|money|outstanding/.test(s)) { const o = INVOICES.filter((i) => i.age > 0); return { title: `${inr(o.reduce((a, i) => a + i.balance, 0) * 1.2 + 420000)} is overdue.`, items: [["Eastern Public School", "₹2.24L", "31–60 days", "/receivables"], ["Royal Residency", "₹1.42L", "60+ days", "/receivables"], ["Bihar Retail Group", "₹1.1L", "31–60 days", "/receivables"]].map(([h, a, b, href]) => ({ id: h, head: "", a, b, href })), note: "₹4.2L is older than 30 days. Total outstanding: ₹16.8L." }; }
  if (/profitable/.test(s)) return { title: "RO / Water service is the most profitable at 42% margin.", items: [["RO / Water", "42% margin"], ["Residential AC", "39%"], ["Appliance repair", "37%"], ["Commercial AC", "36% — highest absolute profit"], ["CCTV", "31% — lowest"]].map(([id, a]) => ({ id, head: "", a, b: "", href: "/reports" })), note: "CCTV margin is dragged down by installation cabling overruns." };
  if (/revenue|customer/.test(s)) { const l = [...CUSTOMERS].sort((a, b) => b.ltv - a.ltv).slice(0, 4); return { title: `${l[0].name} generated the most revenue — ${inr(l[0].ltv)} lifetime.`, items: l.map((c) => ({ id: c.name, head: "", a: `${inr(c.ltv)} lifetime`, b: `${c.assets} assets · ${c.amcs} AMCs`, href: `/customers/${c.id}` })), note: "Top 4 customers contribute 31% of revenue." }; }
  if (/sla|branch/.test(s)) return { title: "Patna has the lowest SLA performance at 86%.", items: [...BRANCHES].sort((a, b) => a.sla - b.sla).map((b) => ({ id: b.name, head: "", a: `${b.sla}% within SLA`, b: `First-time fix ${b.ftf}%`, href: "/teams" })), note: "Patna’s average response is 58 min vs 34 min in Ranchi Central — add capacity in Boring Road and Kankarbagh." };
  return { title: "I can answer questions about jobs, technicians, customers, AMC, parts and revenue.", items: [], note: "Try one of the suggested questions on the left." };
}
