export const ALL = ["dashboard", "orders", "planning", "production", "wip", "raw-materials", "finished-goods", "inventory", "purchase", "suppliers", "quality", "machines", "maintenance", "lines", "packing", "dispatch", "customers", "invoices", "payments", "expenses", "finance", "employees", "reports", "logs", "assistant", "settings", "flow"];

export const ROLES = [
  { id: "owner", label: "Owner / Managing Director", person: "Rakesh Agarwal", title: "Managing Director", modules: ALL, perms: ["Everything", "All reports & margins", "Approve large purchases"] },
  { id: "plant", label: "Plant Head", person: "Ajay Singh", title: "Plant Head", modules: ["dashboard", "orders", "planning", "production", "wip", "raw-materials", "finished-goods", "inventory", "quality", "machines", "maintenance", "lines", "packing", "dispatch", "employees", "reports", "flow", "assistant"], perms: ["Production, output, downtime", "Production planning", "Approve work orders"] },
  { id: "prodmgr", label: "Production Manager", person: "Rohit Sharma", title: "Production Manager", modules: ["dashboard", "orders", "planning", "production", "wip", "raw-materials", "finished-goods", "quality", "machines", "lines", "employees", "flow", "assistant"], perms: ["Work orders", "Shifts & work centers", "Material issue requests"] },
  { id: "purchase", label: "Purchase Manager", person: "Anil Mahto", title: "Purchase Manager", modules: ["dashboard", "planning", "raw-materials", "purchase", "suppliers", "inventory", "assistant"], perms: ["Suppliers", "PR / RFQ / PO", "Goods receipt"] },
  { id: "store", label: "Store Manager", person: "Sunil Yadav", title: "Store Manager", modules: ["dashboard", "raw-materials", "finished-goods", "inventory", "purchase", "packing", "wip", "assistant"], perms: ["Raw material & FG inventory", "Material issue", "GRN"] },
  { id: "quality", label: "Quality Manager", person: "Neha Verma", title: "Quality Manager", modules: ["dashboard", "quality", "production", "finished-goods", "wip", "assistant"], perms: ["Inspections", "Rejections & scrap", "Hold / release batches"] },
  { id: "maint", label: "Maintenance Manager", person: "Manoj Kumar", title: "Maintenance Manager", modules: ["dashboard", "machines", "maintenance", "lines", "assistant"], perms: ["Machines", "Breakdown tickets", "PM schedule"] },
  { id: "dispatch", label: "Dispatch Manager", person: "Deepak Oraon", title: "Dispatch Manager", modules: ["dashboard", "orders", "finished-goods", "packing", "dispatch", "customers", "assistant"], perms: ["Packing", "Dispatch & vehicles", "Delivery status"] },
  { id: "accounts", label: "Accounts Manager", person: "Priya Gupta", title: "Accounts Manager", modules: ["dashboard", "customers", "invoices", "payments", "expenses", "finance", "purchase", "suppliers", "reports", "assistant"], perms: ["Invoices", "Collections", "Supplier payments"] },
  { id: "supervisor", label: "Production Supervisor", person: "Vijay Kumar", title: "Production Supervisor — Line 2", modules: ["dashboard", "production", "lines", "wip", "quality", "machines", "raw-materials", "assistant"], perms: ["Shift production entry", "Material receipt on floor", "Raise breakdown"] },
  { id: "admin", label: "Admin", person: "Neha Verma", title: "Admin & HR", modules: ["dashboard", "employees", "logs", "settings", "assistant"], perms: ["Users & roles", "Configuration", "Audit logs"] },
];
export const OWNER_MODULES = ["dashboard", "orders", "planning", "production", "raw-materials", "machines", "quality", "inventory", "finance", "flow", "assistant"];
